Update the test "cell-sort" to use Map
runtimeverification/k pull request #1206
Opened 2020-04-09 17:05 UTC by andreiburdusa

Co-authored-by: Traian Serbanuta <traian.serbanuta@gmail.com>

2020-04-09 17:21 UTC, andreiburdusa commented on k-distribution/tests/regression-new/cell-sort/test.k
>                      <nextFunction> 0:Int </nextFunction> // It works again if we move this outside of <functions>
Should I move it outside the function so the test would work?

2020-04-13 14:19 UTC, ttuegel commented on k-distribution/tests/regression-new/cell-sort/test.k
>                      <nextFunction> 0:Int </nextFunction> // It works again if we move this outside of <functions>
Yes, I don't think this syntax is supported by the Kore backends. At least, I've never seen it used by the semantics that we try to support.

2020-04-13 15:34 UTC, andreiburdusa commented on k-distribution/tests/regression-new/cell-sort/test.k
>                      <nextFunction> 0:Int </nextFunction> // It works again if we move this outside of <functions>
I think something changed. The test is now passing and in order to keep the changes I had to make before, I had to change `1.test.out`

2020-04-14 21:11 UTC, ttuegel commented
@andreiburdusa Does this work when you `make KOMPILE_BACKEND=haskell`? If so, please make a `cell-sort-haskell` test directory with:

1. a symbolic link to `cell-sort/test.k` and
2. a `Makefile` that sets `KOMPILE_BACKEND = haskell`.

Look at [the Bytes test](https://github.com/kframework/k/tree/master/k-distribution/tests/regression-new/bytes-haskell) for an example.

2020-04-15 10:04 UTC, ehildenb commented
Unless it's absolutely necessary, you shouldn't be updating the Haskell backend submodule in this PR. I think it's _unlikely_ that it's necessary, because the Haskell backend is tested against an _older_ commit of K, so the updates to K should for the most part be able to wait for the haskell-backend submodule update job instead of updating itself.

I'll re-iterate as well, _anyone_ can approve the submodule update jobs, it does _not_ have to be the person requested for review. So if you need the submodule update job to go through and @ttuegel is not around ot approve it, feel free to approve it yourself.

2020-04-15 10:26 UTC, ttuegel commented
The submodule update is not necessary for this pull request.

2020-04-15 10:32 UTC, andreiburdusa commented
@ehildenb @ttuegel 
Sorry, I don't know what action of mine caused the update. And I thought I reverted that using `git rebase -i origin/master`. Maybe I'll just close this pr and open a new one

2020-04-15 13:23 UTC, ehildenb commented
@andreiburdusa another simple option is to just add another commit on top which corrects the submodule commit. Figure out the commit that `origin/master` of K uses for haskell backend, checkout that commit in the submodule, and then use `git add haskell-backend/src/main/native/haskell-backend` to add the submodule, then commit it. Then when you push you should see no update to the submodule here anymore.

2020-04-15 13:25 UTC, ehildenb commented
BTW commit b61336b75b1deed8d7b139176177c8d39def9d78 updates the submodule.

Also, I would recommend _not_ using `git add -u` or `git commit -a`, because if you have any changes to the submodule they'll be added.

Instead, explicitely `git add PATH/TO/FILE` that you need every time, and then do `git commit -m "MESSAGE"`

2020-04-16 08:49 UTC, ehildenb commented
It still appears that there is a change to the LLVM backend submodule included here as well, which should be un-done.

2020-04-16 10:07 UTC, andreiburdusa commented
> @andreiburdusa Does this work when you `make KOMPILE_BACKEND=haskell`? If so, please make a `cell-sort-haskell` test directory with:
> 
>     1. a symbolic link to `cell-sort/test.k` and
> 
>     2. a `Makefile` that sets `KOMPILE_BACKEND = haskell`.
> 
> 
> Look at [the Bytes test](https://github.com/kframework/k/tree/master/k-distribution/tests/regression-new/bytes-haskell) for an example.

No, it doesn't. The Java backand gives the output
```
<T>
  <k>
    "done"
  </k>
  <nextFunction>
    3
  </nextFunction>
  <functions>
    <fId>
      0
    </fId> |-> <function>
      <fId>
        0
      </fId>
    </function>
    <fId>
      1
    </fId> |-> <function>
      <fId>
        1
      </fId>
    </function>
    <fId>
      2
    </fId> |-> <function>
      <fId>
        2
      </fId>
    </function>
  </functions>
  <contracts>
    <cName>
      foo
    </cName> |-> <contract>
      <cName>
        foo
      </cName>
      <cFunctions>
        f1 |-> 0
        f2 |-> 1
        f3 |-> 2
      </cFunctions>
    </contract>
  </contracts>
</T>
```
while the Haskell backand
```
<T>
  <k>
    "done"
  </k>
  <nextFunction>
    3
  </nextFunction>
  <functions>
    <function>
      <fId>
        0
      </fId>
    </function> <function>
      <fId>
        1
      </fId>
    </function> <function>
      <fId>
        2
      </fId>
    </function>
  </functions>
  <contracts>
    <contract>
      <cName>
        foo
      </cName>
      <cFunctions>
        f1 |-> 0
        f2 |-> 1
        f3 |-> 2
      </cFunctions>
    </contract>
  </contracts>
</T>
```

2020-04-17 01:12 UTC, ttuegel requested changes
We should not change the Java backend test at all.

2020-04-17 01:12 UTC, ttuegel commented on k-distribution/tests/regression-new/cell-sort/1.test.out
> +    <function>
This should be the correct output with the Java backend.

2020-04-21 19:20 UTC, ttuegel approved these changes

2020-04-22 10:20 UTC, merged