Implement set union operation per discussion with Tom
runtimeverification/k pull request #1257
Opened 2020-05-05 18:14 UTC by Andrew-Miranti

The Michelson semantics needs a Set union operation, but `_Set_` is not Set union, but rather set concatenation ( See https://github.com/kframework/k/issues/1134 for details ).  So I've written Set union in terms of set difference and concatenation.

2020-05-05 18:35 UTC, dwightguth commented
Please make this a hooked operation SET.union. I will update the llvm backend to add support for this hook.

2020-05-05 18:59 UTC, dwightguth requested changes

2020-05-05 18:59 UTC, dwightguth commented on k-distribution/include/builtin/domains.k
> +  syntax Set ::= Set "USet" Set            [function, functional, hook(SET.union)]
let's make this |Set.

2020-05-05 19:09 UTC, dwightguth approved these changes

2020-06-21 18:00 UTC, nishantjr commented on k-distribution/include/kframework/builtin/domains.k
> +  syntax Set ::= Set "|Set" Set            [function, functional, hook(SET.union)]
```suggestion
  syntax Set ::= Set "|Set" Set            [left, function, functional, hook(SET.union)]
```

2020-06-21 18:02 UTC, nishantjr commented
@dwightguth Reminder about this. I added the `left` attribute to the `|Set` operator after the review.

2020-06-22 12:41 UTC, dwightguth commented
Looks like the test is failing because of the OCAML backend. It shouldn't be hard to fix; just add the hook_union function to the SET module in hooks.ml and make it call hook_concat.

2020-07-08 16:25 UTC, dwightguth commented
It looks like the fix to DefinitionParsing.java in this file might be a fix for the same issue as #1388. At the very least, the fix is related, making the fix for that issue blocked on this PR. I am going to take this PR over and fix the remaining issues so it can be merged.

2020-07-09 18:29 UTC, dwightguth approved these changes

2020-07-13 13:38 UTC, dwightguth commented
Not sure why the map-symbolic test failed, but this PR is no longer blocking me, so I'm going to unassign myself. It might just be some kind of flaky test, or it might be some odd interaction with the changes to DefinitionParsing.java...

2020-07-13 16:21 UTC, merged