Allow making modifications/omissions to the output via command-line flags
runtimeverification/k pull request #157
Opened 2018-09-28 21:44 UTC by ehildenb

2018-09-28 22:43 UTC, dwightguth commented
I'm not sure I like the idea of --output-tostring, the tostring methods on k terms are pretty janky and should not be exposed to users. If it's just a matter of performance, have an --output-kast which just doesn't unparse the term

2018-09-29 00:08 UTC, ehildenb commented
@dwightguth see the newest commit, it makes the switch you suggest. I had to fallback to to `toString` for `UnsupportedEncodingException`, which basically should never happen I think? So more just to appease the exceptions type-system.

2018-10-02 15:24 UTC, dwightguth requested changes
looks good but there are some minor changes that need to be made.

2018-10-02 15:24 UTC, dwightguth commented on kernel/src/main/java/org/kframework/unparser/KPrint.java
> +        this(new KExceptionManager(new GlobalOptions()), FileUtil.testFileUtil(), new TTYInfo(false, false, false), new PrintOptions(), kompileOptions);
I should think this should be kompileOptions.global

2018-10-02 15:24 UTC, dwightguth commented on kernel/src/main/java/org/kframework/unparser/KPrint.java
> +            kastTerm = new String(KPrint.serialize(kapp, OutputModes.KAST), "UTF-8");
You should be able to skip the exception handling here by just calling ToKast directly.

2018-10-02 15:24 UTC, dwightguth commented on kernel/src/main/java/org/kframework/unparser/KPrint.java
> +            kastTerm = new String(KPrint.serialize(kapp, OutputModes.KAST), "UTF-8");
Not to mention the fact that this code currently is going to create mojibake as it serializes the string to the machine's default charset and then tries to parse it with utf-8.

2018-10-02 16:17 UTC, dwightguth approved these changes

2018-10-02 16:50 UTC, merged