Remove KDoc references
runtimeverification/k pull request #1679
Opened 2020-12-01 19:07 UTC by ehildenb

Fixes #41 

The KDoc tool has been non-functional for some time. This removes it from the codebase and the documentation.

2020-12-01 20:52 UTC, radumereuta commented
With this change, are latex attributes used anywhere else?
Shouldn't we remove those too?

2020-12-01 21:23 UTC, ehildenb commented
They are still used by `--output latex` @radumereuta. And #1620 will make it actually use those attributes, so I don't want to remove them yet.

2020-12-02 20:51 UTC, radumereuta requested changes

2020-12-02 20:51 UTC, radumereuta commented on k-distribution/tutorial/1_k/1_lambda/lesson_9/README.md
> +PDF document. This is particularly useful when you want to incorporate
I think this paragraph refers to generating a latex output of the definition. Having latex output for `krun`, `kast` and `kprove` is not really helpful in this case.

2020-12-02 20:51 UTC, radumereuta commented on k-distribution/tutorial/1_k/4_imp++/lesson_8/README.md
> +option `--output latex`, and then visualize the generated PDF document.
Another reference to definition -> latex.

2020-12-08 18:02 UTC, radumereuta requested changes

2020-12-08 18:02 UTC, radumereuta commented on k-distribution/tutorial/1_k/1_lambda/lesson_4/README.md
>  comments and headers to our language definitions, which give us maximum
This paragraph still refers to using latex to format definitions.

2020-12-10 16:52 UTC, radumereuta commented on k-distribution/tutorial/1_k/1_lambda/lesson_4/README.md
>  comments and headers to our language definitions, which give us maximum
I think this paragraph should be reworded to mention Markdown, or even deleted.

2020-12-10 17:10 UTC, radumereuta approved these changes
Looks fine for now.

2020-12-10 19:06 UTC, dwightguth commented on k-distribution/tutorial/1_k/1_lambda/lesson_9/README.md
> +back-ends of the K tool, such as those enabled with the `--output latex`
This seems to be missing a verb.

2020-12-10 20:35 UTC, ehildenb commented on k-distribution/tutorial/1_k/1_lambda/lesson_9/README.md
> +back-ends of the K tool, such as those enabled with the `--output latex`
addressed

2020-12-16 14:30 UTC, dwightguth approved these changes

2020-12-16 17:49 UTC, merged