Issue1682 kore pp
runtimeverification/k pull request #1707
Opened 2020-12-14 01:12 UTC by radumereuta

Fixes: #1682

2020-12-16 14:27 UTC, dwightguth requested changes
I would really like to see variables still be annotated by their sort during unparsing; you can just add the cast during KOREToTreeNodes instead of KOREToK

2021-01-11 21:32 UTC, radumereuta commented
@dwightguth I've done the change, and there are over 200 files that need to be updated with sort annotations.
That was the only file that had them, not sure why.
Are you still sure we want this?

2021-01-12 18:41 UTC, ehildenb commented
Let's preserve the old behavior with the simple annotation (so that we (i) are not making kprove output more verbose, and (ii) we can still correctly call ModuleToKore).

We can do this by making a separate attribute to indicate that a variable needs to be annotated at unparse time because of an injection that lives above it.

2021-01-13 17:59 UTC, dwightguth approved these changes

2021-01-13 18:49 UTC, merged