Debugg: State dumping for Java Backend to enable tools like KLab
runtimeverification/k pull request #175
Opened 2018-10-20 18:37 UTC by ehildenb

State dumping is enabled for `search`, `prove`, and `run` modes uniformly.

2018-10-28 12:03 UTC, ehildenb commented
@dwightguth if @denis-bogdanas confirms there isn't anything that needs fixed immediately with this, can you merge? We'd like to get this in because it's taking a while to get KLab working perfectly with it and there are other more immediate uses.

2018-10-28 20:21 UTC, denis-bogdanas approved these changes
Looks good.

2018-10-29 13:43 UTC, dwightguth requested changes
Some obvious changes that need to be made:

* need to move Debugg to the java backend module, package org.kframework.backend.java, and also rename it to something better like ProofLogging or some such.
* need to move the options you added to somewhere better than GlobalOptionls. If you only need them for proofs, move them to KProveOptions, but if you want them for kprove, krun, and keq then you probably want to add them to JavaExecutionOptions.java and fix the bug that is causing those options to not be exposed on the command line.

2018-10-29 13:43 UTC, dwightguth commented on kore/src/main/scala/org/kframework/builtin/Sorts.scala
> +  val Z3Query  = Sort("Z3Query")
these are not real sorts. Is there a reason why we need to encode these as fake K terms instead of just logging them directly?

2018-11-13 06:13 UTC, denis-bogdanas commented
Any news on this? We have 3 new hires in Bucharest. It would be helpful if they could use KLab.

2018-11-13 16:34 UTC, dwightguth commented
I'd still like to see the code quality improved, but the people who you're talking about could probably work off this branch potentially

2018-11-18 21:15 UTC, ehildenb commented
@dwightguth it doesn't only log in proof mode, also in normal execution and searching execution.

This is needed because we want to be able to use KLab for any execution type, so it doesn't make sense to name it `ProofLogging` because it's just generic logging of the Java backend (which can run in multiple modes).

I can move it to the Java backend package though.

2018-11-18 21:24 UTC, ehildenb commented on kore/src/main/scala/org/kframework/builtin/Sorts.scala
> +  val Z3Query  = Sort("Z3Query")
The thought would be that eventually we'll have an actual sort of Z3Query and Z3Result (when it's integrated more properly). Not sure it will happen in the Java backend, but maybe in the Haskell backend. It also means that anything reading the logs only needs to understand KAST format and will be able to use standard getters to pick out the terms for z3 queries/results.

I can build the sort on the fly instead, but would prefer to call it out specially if we're going to use it specially.

2018-11-18 22:01 UTC, ehildenb commented
Hmmm, actually does moving it to the Java backend package make sense? It needs things from the front-end, for example the unparsing code.

2018-11-19 17:01 UTC, ehildenb commented
Jenkins: test this please

2018-11-19 17:49 UTC, dwightguth commented
The java backend depends on the kernel module so that's fine. If it's not just proving, you can give it another name, but Debugg is still a bad name. Moreover, GlobalOptions is used for options that affect the k framework as a whole and would be included in kompile and kast as well, which still isn't really suitable here. You can put it in JavaExecutionOptions then like I said.

2018-11-21 06:56 UTC, ehildenb commented
@dwightguth I have moved the Debugg to the `java-backend` module, and named it `StateLog` instead.

Also, I looked into the issue with JavaExecutionOptions. I'm not entirely sure, but I believe the problem is that options are exposed to the command line through code that lives in `kernel/`. `JavaExecutionOptions` is in `java-backend/`, but depends on `kernel/`. So when I try to add the import:

```
import org.kframework.backend.java.symbolic.JavaExecutionOptions
```

to `KRunOptions.java` (for example), so that I can do:

```
@ParametersDelegate
public JavaExecutionOptions JavaExecutionOptions = new JavaExecutionOptions();
```

it doesn't even know about the `org.kframework.backend` package (because `kernel` has no knowledge of `java-backend`).

So, I'm not sure what do, I don't think this issue with `JavaExecutionOptions` is directly fixable. So I'm inclined to move the options to `KRunOptions`, which would be a minimal change compared to the existing code but would move them out of `GlobalOptions`.

2018-11-22 17:45 UTC, denis-bogdanas commented
@ehildenb Can you move JavaExecutionOptions to kernel? This class actually contains interesting features.

2018-11-26 12:20 UTC, dwightguth commented
The solution with JavaExecutionOptions is to add a bind statement to the MapBinder of options to the guice modules for the Java backend. Please compare to OcamlKRunOptions for examples.

2018-11-27 00:38 UTC, ehildenb commented
Depends on #204 , closing for now.

2018-11-27 00:38 UTC, closed without merging