Forbid macro att on function rules
runtimeverification/k pull request #1870
Opened 2021-03-19 18:46 UTC by radumereuta

Fixes: #1852

I'm assuming all of these attributes are not allowed on function rules: macro|macro-rec|alias|alias-rec
How about claims. What attributes are not allowed?

2021-03-19 19:25 UTC, radumereuta commented
This is failing: https://github.com/kframework/k/blob/master/k-distribution/tests/regression-new/proof-tests/deposit/spec/deposit-symbolic.k#L8
Are we sure we want to enforce this restriction?

2021-03-22 16:08 UTC, dwightguth commented
Claims can't be macros so you can forbid all of those attributes on claims.

2021-03-22 16:34 UTC, dwightguth requested changes
Please add a test that this check correctly handles rules with function context. You don't seem to have implemented this the usual way, so I'd like to be certain.

2021-03-22 16:34 UTC, dwightguth commented on kernel/src/main/java/org/kframework/compile/checks/CheckFunctions.java
> +                if (isRHS() || k.klabel() instanceof KVariable || !m.attributesFor().contains(k.klabel())) {
Instead of checking isRHS, which will return true outside of any rewrite, you probably want to check `isRHS() && !isLHS()`

2021-03-22 22:10 UTC, radumereuta commented
@dwightguth I added more tests.
I also added the check to `context` and `context alias`. Please confirm which attributes are allowed because I couldn't find hard evidence of what is allowed where.

2021-03-24 18:13 UTC, dwightguth approved these changes

2021-03-25 15:49 UTC, merged