Add definedness conditions to simplification rules in domains.md
runtimeverification/k pull request #1899
Opened 2021-04-05 18:50 UTC by andreiburdusa

Fixes https://github.com/kframework/kore/issues/2487

2021-04-05 20:33 UTC, ehildenb commented on k-distribution/include/kframework/builtin/domains.md
> +  rule (K |-> _ M:Map) [ K <- V ] => (K |-> V M) ensures notBool (K in_keys(M)) [simplification]
Is this not already implied by `K |-> _ M` being a well-defined map?

2021-04-06 14:18 UTC, ttuegel requested changes
These `ensures` clauses are redundant because these simplification rules already preserve `#Bottom`. Let's add comments at each rule explaining why the `ensures` is not needed.

2021-04-07 10:50 UTC, ttuegel requested changes
Please _remove_ the `ensures` clauses and leave a comment explaining that _adding_ them would be redundant.

2021-04-07 21:16 UTC, ttuegel approved these changes

2021-04-09 19:13 UTC, dwightguth approved these changes

2021-04-09 22:50 UTC, merged