Declare encoding/decoding between Bytes and String in domains.md
runtimeverification/k pull request #2002
Opened 2021-06-02 11:30 UTC by andreiburdusa

Fixes #1953

2021-06-07 16:14 UTC, ttuegel requested changes

2021-06-07 16:14 UTC, ttuegel commented on k-distribution/include/kframework/builtin/domains.md
> +You can encode/decode between Bytes and String using`UTF-8`, `UTF-16LE`, `UTF-16BE`, `UTF-32LE`, and `UTF-32BE`
```suggestion
You can encode/decode between Bytes and String using `UTF-8`, `UTF-16LE`, `UTF-16BE`, `UTF-32LE`, and `UTF-32BE`
```

2021-06-07 16:14 UTC, ttuegel commented on k-distribution/include/kframework/builtin/domains.md
> +  imports BYTES-SYNTAX
The new module needs to be included by default: 

```suggestion
  imports BYTES-SYNTAX
  imports BYTES-STRING-ENCODE
```

2021-06-08 15:16 UTC, dwightguth reviewed
Wouldn't it be better if we supported any encoding that was supported by `libiconv`?

2021-06-08 19:29 UTC, ttuegel commented
> Wouldn't it be better if we supported any encoding that was supported by `libiconv`?

The only binding I can find for `libiconv` does not seem to be maintained. The original request was only for UTF-8, so I'm inclined to approve it as-is until we need more.

2021-06-08 19:30 UTC, ttuegel approved these changes

2021-06-08 20:23 UTC, dwightguth approved these changes

2021-06-08 20:49 UTC, merged