Version 5.2
runtimeverification/k pull request #2027
Opened 2021-06-15 16:51 UTC by ehildenb

To Check:

- [ ] File `./package/version` has been bumped to `NEW_MAJOR.NEW_MINOR.0`, and `./package/version.sh sub` has been invoked.
- [ ] `CHANGELOG.md` has been updated with new features.
- [ ] `krun` help script is correctly reflecting the available options
- [ ] All `*Options.java` files are up-to-date.
- [ ] K active projects page is up-to-date (receiving commits in the last 3 months).
- [ ] Audit of warnings in regression test-suite and tutorial.
- [ ] Audit package dependencies in `package/`.

2021-09-30 16:50 UTC, radumereuta commented
Link to the haskell backend changelog.

2021-11-05 18:28 UTC, radumereuta commented
@ehildenb please review.

2021-11-06 15:35 UTC, ehildenb commented on CHANGELOG.md
> +    Bison parser, instead of causing an error.
Inconsistent formatting here?

2021-11-06 15:36 UTC, ehildenb commented on CHANGELOG.md
> +- Added `-I`, `--md-selector` and `--no-prelude` to kprove, kprovex and kbmc
```suggestion
- Added `-I`, `--md-selector` and `--no-prelude` to `kprove`, `kprovex` and `kbmc`.
```

2021-11-06 15:38 UTC, ehildenb commented
Looks good to me. Make sure to look through the checklist at the top of the PR @radumereuta . I've trimmed it down.

2021-11-08 10:14 UTC, Baltoli commented on CHANGELOG.md
> +  several code-paths in `kompile`.
-> allows several code paths in `kompile` to be simplified

2021-11-08 10:17 UTC, Baltoli requested changes

2021-11-08 10:17 UTC, Baltoli commented on CHANGELOG.md
> +  several code-paths in `kompile`.
-> allows several code paths in `kompile` to be simplified

2021-11-08 10:17 UTC, Baltoli commented on CHANGELOG.md
> +- Relicence as BSD 3-Clause
-> relicense

2021-11-08 10:17 UTC, Baltoli commented on CHANGELOG.md
> +-   commons-io Java library is bumped to version 2.7.
The indentation here on list entries is different to above - is this deliberate?

2021-11-11 15:10 UTC, Baltoli approved these changes
Looks good!

2021-11-11 15:25 UTC, ehildenb commented
LGTM! I can't approve because I opened this one a long time ago.

2021-11-11 16:01 UTC, merged