add #let A = B #in C syntax
runtimeverification/k pull request #2082
Opened 2021-07-14 16:48 UTC by dwightguth

Turns out to be pretty simple.

2021-07-14 19:32 UTC, radumereuta requested changes
This could use a test.
If you can piggyback on an existing one that would be even better.
Other than that, the changes to the code look fine.

2021-07-14 19:35 UTC, dwightguth commented
Whoops. Good catch. I wrote a test and apparently forgot to `git add` it

2021-07-14 19:39 UTC, radumereuta approved these changes
I will let @ehildenb add the automerge if he is happy with the functionality.

2021-07-14 19:42 UTC, ehildenb commented on k-distribution/tests/regression-new/let-test/test.k
> +  rule 0 => #let FOO = 1 #in FOO
Let's add a few more rules, specifically one with 1 nested binding, one with 2. If you are happy with the output they give, then feel free to add automerge @dwightguth

2021-07-14 19:43 UTC, ehildenb commented on kernel/src/main/java/org/kframework/compile/RewriteAwareVisitor.java
> +            } else if (k.klabel().name().equals("#fun3")) {
Should this be `#fun3` or `#let`? I guess the next case was handling `#fun3` before, and now this case is handling `#fun3` and the next case is handling `#let`.

2021-07-14 19:44 UTC, ehildenb commented on kernel/src/main/java/org/kframework/compile/RewriteAwareVisitor.java
> +            } else if (k.klabel().name().equals("#fun3")) {
Ah, actually, the cases are identical. Why don't we just do `.equals('#fun3') or .equals('#let')` and have one case?

2021-07-14 22:49 UTC, merged

2021-07-15 03:37 UTC, nishantjr commented
@dwightguth Could we add some documentation please.

2021-07-15 06:50 UTC, nishantjr commented
@dwightguth @ehildenb Are we also thinking about syntax for allowing let bindings that works across cells as well?
Looking at this I don't thing we can do:

```
rule <foo> I => foo(I) </fooK
```