`imports FOO.bar`
runtimeverification/k pull request #2144
Opened 2021-08-18 20:25 UTC by dwightguth

This does not contain any syntax for renaming yet; I am simply focusing on the task of importing specific syntax by its tag.

2021-08-19 20:57 UTC, radumereuta requested changes
This could use some tests.
Some JUnit tests in `OuterParsingTests` for the new syntax and two tests in
`regression-new/checks` one with an error, and one that passes.
I will look into the semantics of this PR tomorrow when I have more energy.

2021-08-19 20:57 UTC, radumereuta commented on kernel/src/main/java/org/kframework/kore/convertors/KILtoKORE.java
> +        return org.kframework.definition.FlatImport.apply(imp.getName(), imp.isPublic(), imp.getTag() == null ? immutable(Optional.empty()) : immutable(Optional.of(Tag(imp.getTag()))), convertAttribu
Line too long.

2021-08-19 20:57 UTC, radumereuta commented on kernel/src/main/java/org/kframework/parser/json/JsonParser.java
> +        jsonimports.getValuesAs(JsonObject.class).forEach(i -> imports.add(FlatImport.apply(i.getString("name"), i.getBoolean("public"), immutable(Optional.ofNullable(i.getString("tag")).map(s -> Tag
Line too long.

2021-08-20 18:04 UTC, nishantjr commented
More tests, please, and documentation too.

2021-08-23 12:34 UTC, radumereuta commented
This is part of #2115

2021-08-23 17:15 UTC, radumereuta requested changes
Overall pretty good. Just the two small changes.

2021-08-23 17:15 UTC, radumereuta commented on k-distribution/tests/regression-new/checks/partialImport.k
> +  rule alsoAFoo() => .K
Can you also add:
```
rule baz() => .K // should fail because we're not importing transitively
rule boo() => .K // should fail because of private import
```
and define it in module C? Just to make sure we're not including C transitively.
And then add a
```
module D [private]
  syntax Boo ::= boo()
endmodule
```
And import this in A.

2021-08-23 17:15 UTC, radumereuta commented on USER_MANUAL.md
> +only productiosn whose klabel attribute is `bar` or whose attribute list
```suggestion
only production whose klabel attribute is `bar` or whose attribute list
```

2021-08-23 17:20 UTC, dwightguth commented on k-distribution/tests/regression-new/checks/partialImport.k
> +  rule alsoAFoo() => .K
If you have a suggested code change, please make it as a suggestion; what you wrote here is ambiguous enough that I can't actually tell what you meant.

2021-08-23 17:32 UTC, radumereuta approved these changes

2021-08-23 20:40 UTC, merged