kompile: allow macros on productions
runtimeverification/k pull request #2272
Opened 2021-10-15 18:12 UTC by SchmErik

This pull request enables macro labels to be used on productions rather than on rules.

Fixes: #1584

2021-10-15 19:09 UTC, radumereuta requested changes
Just a few small issues.
I will go through this again tomorrow. Too tired now for deep logic.
Also, @dwightguth is the most familiar with macros, so he should be the one to do the final approval.

2021-10-15 19:09 UTC, radumereuta commented on kore/src/main/scala/org/kframework/attributes/Att.scala
> +
Is it possible to have multiple labels from this list on the same production?

2021-10-15 19:09 UTC, radumereuta commented on kore/src/main/scala/org/kframework/definition/outer.scala
> +  def matchKLabel(r: Rule) = r.body match {
IntelliJ: Type annotation required for public member.

2021-10-15 19:09 UTC, radumereuta commented on kore/src/main/scala/org/kframework/definition/outer.scala
> +  def ruleLhsHasMacroKLabel(r: Rule) = r.body match {
IntelliJ: Type annotation required for public member.

2021-10-15 19:09 UTC, radumereuta commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/JavaBackend.java
> +                .andThen(m2 -> ModuleTransformer.fromSentenceTransformer((mod, s) -> new PropagateMacro(mod).propagate(s), "propagate macro labels from production to rules").apply(m2))
Line too long.

2021-10-15 20:21 UTC, SchmErik commented on kore/src/main/scala/org/kframework/attributes/Att.scala
> +
it is but it doesn't make sense to have multiple labels. I think this should be a separate check all together

2021-10-16 17:57 UTC, radumereuta commented
I managed to have another look. Plenty of tests and the code lgtm, other than those small surface comments.

2021-10-19 14:49 UTC, radumereuta approved these changes
@dwightguth can you give the final approval?

2021-10-19 15:20 UTC, dwightguth approved these changes

2021-10-19 15:50 UTC, merged