Check for existential variables in requires clause
runtimeverification/k pull request #2336
Opened 2021-11-18 22:55 UTC by SchmErik

The `requires` clause is a part of the LHS of the rule. Since existential
variables are not allowed on LHS of the rule, these variables are not
allowed in the clause. Add a check to catch rules like this.

Fixes: https://github.com/kframework/k/issues/2324

2021-11-18 22:56 UTC, SchmErik commented
converting to draft. Will set this as ready to review after a few tests have been fixed: https://github.com/kframework/k/issues/2324

2021-11-19 22:06 UTC, SchmErik commented on k-distribution/tests/regression-new/spec-rule-application/def02-spec.k.out
> -#Top
@radumereuta Changing the def02-spec.k resulted in a different test output. Is this the correct approach??

2021-11-22 18:31 UTC, radumereuta requested changes

2021-11-22 18:31 UTC, radumereuta commented on k-distribution/tests/regression-new/bisimulation/examples/program-equivalence/imp-lambda/simple-spec.k
> + andBool Ks1 ==K Ks2
`andBool _Ks1 ==K _Ks2`
Don't forget about underscore, otherwise you will get warnings.

2021-11-22 18:31 UTC, radumereuta commented on k-distribution/tests/regression-new/spec-rule-application/def02-spec.k
> +      requires Z ==Int incPos(Y)
`?Z` appears in two locations. You need to update both. Otherwise, you will get two different variable names.

2021-11-22 20:25 UTC, radumereuta approved these changes

2021-11-23 19:09 UTC, merged