Add warning for syntax priority / associativity mismatch
runtimeverification/k pull request #2710
Opened 2022-07-07 14:22 UTC by Baltoli

Fixes #2460 

This PR adds a compiler check that the labels in a syntax associativity sentence are not in different priority groups, and updates the relevant sections of the K tutorial and user manual to reflect this.

Note that the error message doesn't have location information, because the `SyntaxAssociativity` sentence that I use in the check doesn't seem to include any - is there a better way to phrase this implementation?

2022-07-07 15:58 UTC, ehildenb commented
Grab location information here and make sure it's preserved in the KAST that is produced: https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/kore/convertors/KILtoKORE.java#L141

2022-07-08 17:40 UTC, radumereuta requested changes
Two minor issues.

2022-07-08 17:40 UTC, radumereuta commented on k-distribution/tests/regression-new/syntax-groups/syntaxGroups.k
> +endmodule
We can move this test to `regression-new/checkWarns` to keep things organized.

2022-07-08 17:40 UTC, radumereuta commented on kernel/src/main/java/org/kframework/compile/checks/CheckSyntaxGroups.java
> +            Set<Tag> tags = JavaConverters.setAsJavaSet(((SyntaxAssociativity) s).tags());
Usually we use `mutable` from `collections.scala`
You will need to add
```
import static org.kframework.Collections.*;
```
```suggestion
            Set<Tag> tags = mutable(((SyntaxAssociativity) s).tags());
```

2022-07-14 10:08 UTC, radumereuta approved these changes

2022-07-19 16:22 UTC, dwightguth approved these changes

2022-07-19 16:22 UTC, merged