Build Debian Package on Xenial and Stretch
runtimeverification/k pull request #274
Opened 2019-01-29 20:21 UTC by dwightguth

This should expand the OSes we support to include Ubuntu 16.04, Ubuntu 18.04, and Debian Stretch. Next PR I will investigate Arch Linux and CentOS 7. But I wanted to get the refactorings to the pipeline reviewed first.

2019-01-30 06:27 UTC, traiansf reviewed
Although changes look good, I don't feel qualified to review this.  I guess I could try to test that k works on the distributions we mention if you think that would help.

2019-01-30 18:20 UTC, dwightguth commented
The PR actually tests K on those distributions. I'm fine with Everett reviewing though.

2019-01-30 19:52 UTC, traiansf approved these changes

2019-01-30 21:45 UTC, ehildenb requested changes
Things look good except that it's clogging up the CI server severely. Lets reduce the parallelism to keep that from happening.

2019-02-04 21:36 UTC, ehildenb reviewed
Looks good, except for one thing I'm wondering about.

2019-02-04 21:36 UTC, ehildenb commented on Dockerfile
> +RUN mvn dependency:go-offline
Should this be `cd ...`ing to the correct directory first?

2019-02-04 21:53 UTC, ehildenb approved these changes

2019-02-05 18:25 UTC, merged