Duplicate comm simplification rules
runtimeverification/k pull request #2754
Opened 2022-07-28 13:31 UTC by radumereuta

Fixes: #2587

2022-07-28 14:27 UTC, radumereuta commented
Failing with this message. Coming from the java backend: https://github.com/runtimeverification/k/blob/master/java-backend/src/main/java/org/kframework/backend/java/kil/Definition.java#L176
```
     [exec] [Error] Critical: Unexpected combination of assoc, comm, idem attributes found.
     [exec] Currently only sets, maps, and lists are supported: syntax {Sort1, Sort2} Sort2
     [exec] ::= "{" Sort1 "#Equals" Sort1 "}" [comm, format(%1%i%n%2%d%n%3%i%n%4%d%n%5),
     [exec] klabel(#Equals), mlEquals, mlOp, symbol]
     [exec] 	Source(/home/jenkins-runner/workspace/K_PR-2754/k-distribution/target/release/k/include/kframework/builtin/kast.md)
     [exec] 	Location(148,35,148,148)
     [exec] 	148 |	                                | "{" Sort1 "#Equals" Sort1 "}" [klabel(#Equals), symbol, mlOp, mlEquals, comm, format(%1%i%n%2%d%n%3%i%n%4%d%n%5)]
```

2022-07-28 15:06 UTC, radumereuta commented
Hack the Java backend to remove the `comm` attribute in Definition.java.
Only if there is no assoc or idem present.
If we find issues with the LLVM backend we should talk again.
We should test it with some larger semantics as well.

2022-07-30 05:27 UTC, ehildenb commented on kernel/src/main/java/org/kframework/compile/ResolveComm.java
> +                if ((isRHS() && !isLHS()) || k.klabel() instanceof KVariable || !m.attributesFor().contains(k.klabel())) {
Is this only swapping at the top-most position of the LHS, or at every position with a `comm` symbol? We should only swap at the top-most position.

For example, if we have:

```
    rule { 1 +Int 2 #Equals 3 } => #Top [comm]
```

It should generate rule:

```
    rule { 3 #Equals 1 +Int 2 } => #Top
```

But not rule:

```
    rule { 3 #Equals 2 +Int 1 } => #Top
```

2022-07-30 05:27 UTC, ehildenb commented on kernel/src/main/java/org/kframework/compile/ResolveComm.java
> +                if ((isRHS() && !isLHS()) || k.klabel() instanceof KVariable || !m.attributesFor().contains(k.klabel())) {
Maybe this could be added as a test somehow.

2022-08-02 13:52 UTC, ehildenb approved these changes

2022-08-02 18:10 UTC, dwightguth requested changes
I'd definitely like to see tests for this.

2022-08-04 15:14 UTC, radumereuta commented
Try to remove the `comm` attribute from the rules generated by this step.

2022-08-04 16:09 UTC, radumereuta commented
I need to test it to see what happens if I add `comm` to more productions since the backend generates extra axioms for each.

2022-08-04 16:46 UTC, dwightguth approved these changes
looks fine. Adding the commutativity axioms to the kore definition shouldn't affect anything though since both backends appear to be ignoring them.

2022-08-04 16:46 UTC, ehildenb commented
Please add an issue to identify what's going on with the backend, so we can get that fixed too. The backends should not have to have the `comm` attribute stripped.

2022-08-04 16:47 UTC, merged