Fix Stopwatch formatting.
runtimeverification/k pull request #278
Opened 2019-01-30 19:39 UTC by radumereuta

This was partially changed in #178. Now fixing the other print location.
Before:
```
Cleanup                                                      = 0.001 s
Total                                                        = 6056
```
After:
```
Cleanup                                                      = 0.001 s
Total                                                        = 6.056 s
```
Also, if the total time is more than one minute it should show:
```
Cleanup                                                      = 0.001 s
Total                                                        = 75.056 s (1m 15s)
```

2019-01-30 23:28 UTC, dwightguth requested changes
if you're going to change how times longer than a minute are printed, change it consistently and appropriately in both places with a helper method and using a mechanism that scales up to durations longer than an hour.

2019-01-30 23:28 UTC, dwightguth commented on kernel/src/main/java/org/kframework/utils/Stopwatch.java
> +            double ms = (lastIntermediate - start) / 1000.;
this is named ms but it seems to be a number of seconds, which is wildly misleading.

2019-01-31 13:37 UTC, radumereuta commented
Good points. There are a few automatic convertors, but I couldn't find any that I liked so I've implemented something custom. It should now print:
```
Cleanup                                                      =  7.135s
Total                                                        = 17.135s
```
Or for longer times:
```
 0.000s
 0.100s
10.000s
16m 40s
27h 46m 40s
277h 46m 40s
```

2019-01-31 18:36 UTC, dwightguth approved these changes

2019-01-31 20:28 UTC, radumereuta commented
@dwightguth do you have any idea why the deb package step failed?

2019-02-01 01:40 UTC, merged