Add section `Profiling your K semantics` section in the user manual.
runtimeverification/k pull request #2809
Opened 2022-08-16 13:58 UTC by ChristianoBraga

The new section, right after `Debugging`, gives a general description of the process necessary for profiling and illustrates it with a couple of Makefile target examples from the KPlutus project.

2022-08-17 14:39 UTC, radumereuta reviewed
Just some minor aesthetic changes.
Suggestions from the makefile blocks removes trailing whitespace so it doesn't introduce a horizontal scroll bar in the rendered version.

I would still like it this gets one more review from @dwightguth or @ehildenb

2022-08-17 14:39 UTC, radumereuta commented on USER_MANUAL.md
> +3. Next, you build the semantics with optimizations and debug info enabled (i.e., kompile -O3 -ccopt -g )
```suggestion
3. Next, you build the semantics with optimizations and debug info enabled (i.e., `kompile -O3 -ccopt -g` )
```

2022-08-17 14:39 UTC, radumereuta commented on USER_MANUAL.md
> +```
```suggestion
```makefile
k-deps-profiling: K_MVN_ARGS += -Dhaskell.backend.skip=true
k-deps-profiling: K_BUILD_TYPE := FastBuild
k-deps-profiling: export CMAKE_CXX_FLAGS='-O2 -DNDEBUG -fno-omit-frame-pointer'
k-deps-profiling: k-deps
```
```

2022-08-17 14:39 UTC, radumereuta commented on USER_MANUAL.md
> +```
```suggestion
```makefile
build-llvm-profiling: KOMPILE_OPTS += -O3 -ccopt -fno-omit-frame-pointer
build-llvm-profiling: $(KPLUTUS_LIB)/$(llvm_kompiled)
```
```

2022-08-18 18:05 UTC, dwightguth requested changes

2022-08-18 18:05 UTC, dwightguth commented on USER_MANUAL.md
> +export CFLAGS="-g -O2 -fno-omit-frame-pointer"; export CXXFLAGS="-g -O2 -fno-omit-frame-pointer"
let's add `-DNDEBUG` but remove `-g` here.

2022-08-18 18:05 UTC, dwightguth commented on USER_MANUAL.md
> +mvn package -Dproject.build.type="RelWithDebInfo"
This is out of date; I would recommend using `FastBuild` instead as `RelWithDebInfo` enables LTO which does not cooperate very well with `-fno-omit-frame-pointer`.

2022-08-18 18:05 UTC, dwightguth commented on USER_MANUAL.md
> +3. Next, you build the semantics with optimizations and debug info enabled (i.e., `kompile -O3 -ccopt -g` )
-O3 enables at least one optimization in the llvm backend that can cause some issues in some cases. It's probably better to recommend `kompile -ccopt -O2 --iterated`.

2022-08-18 18:05 UTC, dwightguth commented on USER_MANUAL.md
> +## Makefile target examples
I think this section just makes the above more confusing and should probably be removed.

2022-08-30 23:05 UTC, ehildenb commented on USER_MANUAL.md
> +<!-- _(This is this [post](https://runtimeverification.slack.com/archives/C7E701MFG/p1578937371082200), by @dwightguth, with minor changes in prose and formatting.)_ -->
Remove this comment.

2022-08-30 23:06 UTC, ehildenb commented
The rest of the file is wrapped at 80 characters I believe @ChristianoBraga . Please follow the same convention.

2022-08-30 23:09 UTC, dwightguth commented
As a matter of fact, because of how terminals that are exactly 80 characters wide tend to work, the entire file is word wrapped such that each line (with the exception of some code fragments that aren't easy to effectively wrap) is *less than* 80 characters, as in, the 79th character is the last one that is allowed to exist.

2022-09-01 21:17 UTC, ehildenb commented on USER_MANUAL.md
> +
@ChristianoBraga the formatting got messed up here, I guess you called `format` to do the line wrapping.

Please make sure to review the changes yourself (self-review) in browser.

2022-09-03 20:26 UTC, ehildenb commented on USER_MANUAL.md
> +libraries will not have correct stack trace information, which means
Look at the rest of this flie, and format this the same way as the rest.

A space before the backticks codeblock, a space after it, no spaces before each line in the code block, etc...

You should _always_ inspect the formatting of th erest of the file or project or whatever you're contributing to, it's up to you, the PR author, to make sure this is correct. Burden should not be shifted onto the reviewers.

2022-09-04 13:46 UTC, ChristianoBraga commented
I dont’t understand why this was assigned to me in the first place.

Please reassign it to someone who is responsible for formatting the
documentation of K.

On Sat, 3 Sep 2022 at 17:26 Everett Hildenbrandt ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In USER_MANUAL.md
> <https://github.com/runtimeverification/k/pull/2809#discussion_r962198717>
> :
>
> > +optimization_. For example, for EVM, this means rebuilding GMP, MPFR,
> +JEMalloc, Crypto++, SECP256K1, etc with the following `exports`.
> +```shell
> +  export CFLAGS="-g -O2 -fno-omit-frame-pointer" ;
> +  export CXXFLAGS="-DNDEBUG -O2 -fno-omit-frame-pointer"
> +```
> +
> +You can skip this step, but if you do, any samples within these
> +libraries will not have correct stack trace information, which means
>
> Look at the rest of this flie, and format this the same way as the rest.
>
> A space before the backticks codeblock, a space after it, no spaces before
> each line in the code block, etc...
>
> You should *always* inspect the formatting of th erest of the file or
> project or whatever you're contributing to, it's up to you, the PR author,
> to make sure this is correct. Burden should not be shifted onto the
> reviewers.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/runtimeverification/k/pull/2809#pullrequestreview-1095556295>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNNCEPDYX4A2DZERAEKWL3V4OYANANCNFSM56V6L4XQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-08 23:34 UTC, ehildenb approved these changes

2022-09-08 23:36 UTC, ehildenb commented on USER_MANUAL.md
> +export CFLAGS="-g -O2 -fno-omit-frame-pointer"; export CXXFLAGS="-g -O2 -fno-omit-frame-pointer"
@dwightguth is this suggested change supposed to be for both CFLAGS and CXXFLAGS? Currently, we are saying `-DNDEBUG` for `CXXFLAGS`, but `-g` for `CFLAGS`.

2022-09-09 19:01 UTC, dwightguth commented on USER_MANUAL.md
> +export CFLAGS="-g -O2 -fno-omit-frame-pointer"; export CXXFLAGS="-g -O2 -fno-omit-frame-pointer"
Both

2022-09-09 19:02 UTC, dwightguth approved these changes

2022-09-12 03:39 UTC, ehildenb commented on USER_MANUAL.md
> +```
```suggestion
```sh
export CFLAGS="-DNDEBUG -O2 -fno-omit-frame-pointer" ;
export CXXFLAGS="-DNDEBUG -O2 -fno-omit-frame-pointer"
```
```

2022-09-12 03:40 UTC, ehildenb commented on USER_MANUAL.md
> +export CXXFLAGS="-DNDEBUG -O2 -fno-omit-frame-pointer"
`````suggestion
```sh
export CFLAGS="-DNDEBUG -O2 -fno-omit-frame-pointer"
export CXXFLAGS="-DNDEBUG -O2 -fno-omit-frame-pointer"
```
`````

2022-09-12 05:46 UTC, merged