Java Backend Logging: First batch of logging features
runtimeverification/k pull request #291
Opened 2019-02-08 17:11 UTC by denis-bogdanas

## Main additions
- option --log to print a subset of configuration specified in `--log-cells` at each step.
- option --log-basic - same as --log but only at certain important steps such as branchings, application of spec rule.
  Plus enables multiple other minor logs.
- option --log-cells. Generalized logging. Added ability to specify the list of cells to log, and which of these cells to be pretty-printed.
- option --branching-allowed to limit branchings. If allowed number of branchings is exceeded, execution ends.
- option --log-rule, prints rule source for all invoked rules of in all contexts. Both kprove and krun.
- final implication debug: Logging the non-matching sub-terms when final implication does not match, if at least --log-basic is provided.

## Minor additions
- added parameter `step` to some methods, for debugging.
- Custom formatting when entire term is printed, without using the slow pretty printing.
- Better formatting for ConjunctiveFormula. Makes all formulas in debug log more legible.
- Print a message whenever new path condition is created.
- ConjunctiveFormula: Using function isFalseExtended() instead of isFalse() in more contexts.
  The difference is that isFalseExtended() performs contradiction elimination.
  (the only non-logging change in this commit).

## Profiling
- Z3 implications are now divided into ~7 categories based on the place that invokes them, and profiled separately.
- Z3 constraints are similarly divided into ~8 categories based on their context.
- Option `--debug-z3` that logs each ConjunctiveFormula that reaches Z3 solver, along with most important information. It also logs the source code of actual rule that triggered the formula. Orders of magnitude more laconic than --debug. Recommended option for work with kevm proofs.
- Option `--debug-z3-queries` that in addition to `--debug-z3` prints the actual Z3 queries and the source of Z3 anonymous variables. Essential for Z3 debugging.
- Separate SMT warnings at init time from SMT warnings at execution time.
- Count failed z3 queries separately.
- Count separately proved and failure queries for each category.

2019-02-13 19:47 UTC, denis-bogdanas commented
@ehildenb ready for review.

2019-02-15 17:38 UTC, ehildenb requested changes

2019-02-15 17:38 UTC, ehildenb commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/JavaExecutionOptions.java
> +    @Parameter(names="--log", description="Log every step. KEVM only.")
This isn't accurate anymore, AFAICT.

2019-02-15 17:38 UTC, ehildenb commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/JavaExecutionOptions.java
> +                    " All custom logging only works for KEVM-based specs.")
Same here.

2019-02-15 20:43 UTC, denis-bogdanas commented
@ehildenb done.

2019-02-15 21:23 UTC, ehildenb approved these changes

2019-02-16 15:26 UTC, merged