Automatically import BOOL when strictness is applied
runtimeverification/k pull request #3036
Opened 2022-11-08 19:30 UTC by radumereuta

Fixes: #2564
This is done for the compiled definition so we don't taint program parsing.

2022-11-09 11:23 UTC, Baltoli approved these changes

2022-11-10 15:50 UTC, dwightguth requested changes, later dismissed
We should generally be very careful about automatically importing things.

Before we merge this, please check whether importing BOOL into the main module fixes this issue; if it does, we should probably just fix the error message.

2022-11-10 16:13 UTC, ehildenb commented
@dwightguth you can't even write a `requires` clause without `BOOL` being imported. Do we implicitly import bool in other contexts? What about `Map` module for configurations?

I think we should likely follow whatever we're doing elsewhere. As long as it's documented well, we should be OK with it. But I guess it should be disabled if the user wants too (eg. `--no-implicit-imports` or extend `--no-prelude`).

2022-11-10 16:15 UTC, ehildenb commented
The 95% case is that users want to have BOOL implicitly imported, but we should have an escape hatch (credit to Bruce). I think I agree with this.

2022-11-10 16:16 UTC, dwightguth commented
Sounds like the consensus is that this should just work, so I'll rescind my review.

2022-11-10 16:16 UTC, ehildenb commented on k-distribution/tests/regression-new/checks/checkStrictBOOLInclusion.k
> +// imports BOOL
```suggestion
   imports private BOOL
```

2022-11-10 16:17 UTC, ehildenb commented on k-distribution/tests/regression-new/checks/checkStrictBOOLInclusion.k
> +// imports BOOL
Would this work? Is this a workaround?

2022-11-10 19:00 UTC, radumereuta commented
A summary:
1. crashing with `key not found: _andBool_` when we add strict inside the syntax module is clearly not acceptable.
2. manually adding `imports private BOOL` won't work because it's going to taint the program syntax.
 ```console
$ kast -e 'true andBool false'
`_andBool_`(#token("true","Bool"),#token("false","Bool"))
```
3. `ResolveStrict` generates the rules in place. So importing `BOOL` only in the main module won't fix the problem.
4. we have precedence with implicit imports when parsing the configuration. We [import MAP](https://github.com/runtimeverification/k/blob/master/kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java#L282).
5. right now it's failing in the _95% of cases_. Let's have a _5% case_ and see how that workaround should behave. I'm importing the module by name, so if you define your own `domains.md` with your own `BOOL`, then you can override the contents.

One thing I agree with is that documentation should be updated, so I pushed another commit. Please re-review.

2022-11-10 19:01 UTC, radumereuta commented on k-distribution/tests/regression-new/checks/checkStrictBOOLInclusion.k
> +// imports BOOL
Tested, doesn't work, see my latest comment.

2022-11-10 19:35 UTC, ehildenb approved these changes

2022-11-11 14:18 UTC, Baltoli approved these changes

2022-11-11 15:45 UTC, merged