Java Backend error logging: FastRuleMatcher: improved exception handling
runtimeverification/k pull request #326
Opened 2019-03-01 13:45 UTC by denis-bogdanas

2019-03-04 18:20 UTC, dwightguth approved these changes

2019-03-04 18:27 UTC, dwightguth requested changes
I've decided that we probably shouldn't catch Throwable here like this.

2019-03-04 18:32 UTC, dwightguth commented
If you could fix the other case where you're catching Throwable and then executing code that performs allocations afterwards as well, I'd appreciate it. I didn't spot it during review or I would have asked it to be fixed.

2019-03-05 19:52 UTC, denis-bogdanas commented
Ok I changed as you asked. Catching RuntimeException, AssertionError, StackOverflowError.

2019-03-05 20:00 UTC, dwightguth approved these changes

2019-03-05 21:09 UTC, merged