Introduces `--execute-to-branch` to `krun` when using LLVM Backend
runtimeverification/k pull request #3407
Opened 2023-05-10 18:29 UTC by Robertorosmaninho

This PR modifies `krun` tool to add the option `--execute-to-branch`, which is now supported by the LLVM Backend when the user wants to print the current state when the search execution finds a branch. 

The PR that implements the feature on the LLVM Backend is https://github.com/runtimeverification/llvm-backend/pull/756
The issue requesting this feature is https://github.com/runtimeverification/llvm-backend/pull/756#:~:text=close%20these%20issues.-,Support%20for%20search%20execution%20until%20first%20occurrence%20of%20branching,-Notifications

2023-05-10 20:36 UTC, dwightguth requested changes
A couple comments. First, I'd love to be tagged for review in changes to the llvm backend and k frontend in the future. I might not always review them, and that's okay, but it helps bring them to my attention, which is good, because there's several things I'd like to point out here:

1. The usage message is supposed to be in alphabetical order, but the new flag has been placed in the wrong spot.
2. The Haskell backend also supports this flag and if we're adding this flag to the frontend, it should get propagated to both backends and it shouldn't be labeled as specific to the llvm backend.

2023-05-15 09:20 UTC, Baltoli approved these changes
One minor comment; otherwise looks good. Needs to wait for https://github.com/runtimeverification/llvm-backend/pull/756 to be fully propagated before we can merge.

2023-05-15 09:20 UTC, Baltoli commented on k-distribution/src/main/scripts/bin/krun
> +      --execute-to-branch  Execute until the proof branches.
The execution here is not necessarily a proof; in the case of the LLVM backend it's a non-deterministic program

2023-05-15 11:17 UTC, Robertorosmaninho commented on k-distribution/src/main/scripts/bin/krun
> +      --execute-to-branch  Execute until the proof branches.
"execution path" would be a good replace for "proof" here?

2023-05-15 11:21 UTC, Baltoli commented on k-distribution/src/main/scripts/bin/krun
> +      --execute-to-branch  Execute until the proof branches.
> Execute until a non-deterministic state is reached, then exit.
Requires the `--enable-search` option to have been passed to `kompile` on the LLVM backend.

2023-05-15 11:24 UTC, Robertorosmaninho commented on k-distribution/src/main/scripts/bin/krun
> +      --execute-to-branch  Execute until the proof branches.
Thanks!

2023-05-16 12:40 UTC, dwightguth approved these changes

2023-05-16 13:05 UTC, merged