add z3 and rule application feedback functionality
runtimeverification/k pull request #343
Opened 2019-03-07 16:16 UTC by mhhf

This adds additional rule attempt functionality to klab.

2019-03-07 17:59 UTC, dwightguth commented
Looks good to me but I want Everett to review.

2019-03-09 20:53 UTC, ehildenb requested changes
Small nit, also the documentation in file `PrintOptions.java` must be updated as well.

2019-03-09 20:53 UTC, ehildenb commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/SymbolicRewriter.java
> +                global.stateLog.log(StateLog.LogEvent.RULEATTEMPT, specRule.toKRewrite(), constrainedTerm.term(), constrainedTerm.constraint());
Let's make a new event log `SRULEATTEMPT` for this, it may be useful to know that we're attempting a spec rule.

2019-03-13 14:31 UTC, ehildenb approved these changes

2019-03-13 14:45 UTC, merged