Make generated config attributes internal
runtimeverification/k pull request #3587
Opened 2023-08-18 18:57 UTC by gtrepta

More stuff for #3481 . The `CheckAtt` step happens after the definition has been populated with sentences for the configuration, so some of the attributes it's checking weren't actually added by the user. Changing these attributes to internal will make some checks I'm adding for attribute/sentence restrictions a little cleaner.

There are `cell` and `internal` attributes used here in the `RULE-CELLS` module in `kast.md` which could be addressed later.
https://github.com/runtimeverification/k/blob/3d7841ae51afe44a64931a0692be5c41d6c7e67c/k-distribution/include/kframework/builtin/kast.md?plain=1#L287-L295

2023-08-18 20:33 UTC, dwightguth commented
I think the reason why these attributes weren't marked as internal is because it is intended that a configuration declaration is identical in semantics to the same set of productions and rules that it generates. That requires users to be able to write the productions that it corresponds to themselves.

2023-08-18 20:34 UTC, dwightguth commented
Also, the initial attribute isn't dead. It controls how the initializer for cells with multiplicity attribute is generated.

2023-08-18 20:40 UTC, dwightguth requested changes
Marking this as requesting changes. See my comments above. I don't want to just close this PR on you, but I don't think this particular set of changes makes sense

2023-08-18 20:49 UTC, gtrepta commented
> a configuration declaration is identical in semantics to the same set of productions and rules that it generates. That requires users to be able to write the productions that it corresponds to themselves.

Why that requirement?

> Also, the initial attribute isn't dead. It controls how the initializer for cells with multiplicity attribute is generated.

Can you show me an example where the if block I deleted actually gets reached? It was introduced in a commit that added the ocaml backend, and it was never covered when I changed it to just throw an exception.

2023-08-18 21:31 UTC, gtrepta commented
Closing this for now.

2023-08-18 21:31 UTC, closed without merging

2023-08-21 15:41 UTC, dwightguth commented
@gtrepta one reason why we might want to do what I described is if we ever want to parse a k definition, serialize the parsed definition to disk, then reload and finish compiling it later. I could very easily see pyk choosing to do this at some point in the future.

I'm not entirely sure where an example might exist, but essentially, if you have a cell of multiplicity `?`, the attribute controls whether the cell starts out initialized or starts out empty.