Fix edge case in parsing comments in bubbles
runtimeverification/k pull request #3612
Opened 2023-08-30 17:40 UTC by gtrepta

Fixes #3501

2023-08-30 18:28 UTC, dwightguth requested changes
Needs a test. The linked issue contains one. You also need a test for a block comment in the middle of a bubble.

2023-08-30 20:27 UTC, gtrepta commented
Looks like the performance tests have the added benefit of catching problems in downstream semantics

https://github.com/runtimeverification/k/actions/runs/6029210633/job/16359659191?pr=3612#step:7:42

2023-08-31 10:06 UTC, radumereuta requested changes

2023-08-31 10:06 UTC, radumereuta commented on k-distribution/tests/regression-new/issue-3501-bubble-blockcomments/test.k
> +endmodule
This test can be added here: https://github.com/runtimeverification/k/blob/master/kernel/src/test/java/org/kframework/parser/outer/OuterParsingTests.java
with lower performance costs.
Or at most in the `/regression-new/checks` folder.

2023-09-19 15:59 UTC, closed without merging