Escaping back ticks and backslashes in Kast
runtimeverification/k pull request #37
Opened 2018-03-08 23:00 UTC by traiansf

Do not review yet

2018-03-09 00:39 UTC, dwightguth requested changes
I would rather we use String.replace rather than relying on scala magic as it is likely to compile down to much better bytecode.

2018-03-15 20:27 UTC, dwightguth commented
looks like you may need to update some unit tests.

2018-03-16 13:58 UTC, traiansf commented
@dwightguth is it ok now?

2018-03-16 14:06 UTC, dwightguth approved these changes

2018-03-16 14:06 UTC, merged