Implemented injection compaction for the KORE rewrite rule generator.
runtimeverification/k pull request #398
Opened 2019-04-05 17:30 UTC by theo25

This PR fixes a bug where a nested injection could be generated in the output KORE when the input definition contained an injection that contains a rewrite that contains an injection. The fix compacts such nested injections using the injection transitivity axiom.

2019-04-05 18:43 UTC, dwightguth requested changes

2019-04-05 18:43 UTC, dwightguth commented on kore/src/main/scala/org/kframework/compile/RewriteToTop.scala
> +    case t: KApply => compactInjections(KApply(t.klabel, immutable(t.klist.items) map toRight, t.att))
can we do this on toLeft too?

2019-04-05 22:55 UTC, theo25 commented on kore/src/main/scala/org/kframework/compile/RewriteToTop.scala
> +    case t: KApply => compactInjections(KApply(t.klabel, immutable(t.klist.items) map toRight, t.att))
Done

2019-04-08 15:53 UTC, dwightguth approved these changes

2019-04-08 23:46 UTC, merged