[WIP] Support for debugging stuck configurations
runtimeverification/k pull request #61
Opened 2018-05-07 11:36 UTC by h0nzZik

When a function evaluation gets stucked, the user is given only the stucked term. With this patch the user is given a full stacktrace - a chain of terms ranging from the stucked term to the full configuration.

An example:
```bash
$ cd k-distribution/tests/ocaml-backtrack
$ kompile arith.k
$ krun inputs/input_side_stuck3.txt

< Stack trace >

Level: 3
isNice(#token("0", "Int"))

Level: 2
isPretty(#token("0", "Int"))

Level: 1
isBeautiful(#token("0", "Int"))

Level: 0
`<T>`(`<k>`(`_/__ARITH-SYNTAX`(#token("9", "Int"), #token("0", "Int"))))

</Stack trace >

<T>
  <k>
    9 / 0
  </k>
</T>
```
Notes:
* RV-Match needs a small patch to work with this.
* I haven't measured the performance impact. 
* TODO maybe add a switch to `kompile` to enable / disable this feature?
* TODO move the tests to appropriate directory and automate them

@dwightguth Could you please review this?
@chathhorn This is the feature I was talking about recently.

2018-05-07 16:09 UTC, dwightguth requested changes
this pull request has serious structural flaws that need to be addressed before I am comfortable with code that introduces functionality like this being merged. The biggest problems are that you seem to be breaking major abstraction boundaries in order to introduce this functionality, and that you seem to be substantially altering the primary code path of execution in order to introduce a change that should have no bearing on correctly executing semantics. The code needs to be seriously rewritten before it can be merged.

2018-05-07 16:09 UTC, dwightguth commented on k-distribution/include/ocaml/run.ml
> +      check_stack stack;
this doesn't seem right. you are potentially throwing a stuck exception at a point in the code where the rewriting is not necessarily stuck.

2018-05-07 16:09 UTC, dwightguth commented on k-distribution/include/ocaml/run.ml
> +type stepper_func = (k * int) -> (k * int)
I'm not comfortable with how complicated this segment of code is. You're introduced a whole bunch of new functions without it being clear why a pull request concerned primarily with error reporting should be altering the main rewriting code path so significantly. I'd prefer these changes to be localized to the portion of the code dealing with stuck configurations.

2018-05-07 16:09 UTC, dwightguth commented on ocaml-backend/src/main/java/org/kframework/backend/ocaml/DefinitionToOcaml.java
> +		sb.append("let () = if (length stack) <> 1 then print_string (print_stacktrace stack) \n");
I'm not sure I'm really comfortable with this being dumped on stdout without any kind of control happening here. It breaks the architecture of krun to be printing stuff to stdout like this. I'd feel a lot better if the terms were serialized to the java frontend and pretty printed there.

2018-05-07 16:09 UTC, dwightguth commented on ocaml-backend/src/main/java/org/kframework/backend/ocaml/DefinitionToOcaml.java
> +        sb.append("let res = hd (rev stack)\n");
you seem to be doing this a lot, and it seems to me it could be very expensive in the case of a stack overflow. You should probably set a limit on how many stack frames get serialized, and also keep the bottom of the stack at the front of the list so you don't have to pay a linear cost.

2018-05-07 16:09 UTC, dwightguth commented on ocaml-backend/src/main/java/org/kframework/backend/ocaml/DefinitionToOcaml.java
> +                        sb.append(" ([Int counter]) config [config] (-1))\n");
again, I'm not comfortable with us changing the primary code path of execution so substantially just to introduce more error reporting. If you need to construct the stack trace when you reach a stuck configuration, use a series of try blocks.

2018-09-23 19:30 UTC, h0nzZik commented
@dwightguth Ok, I would like to do it the right way now. What do you think about the following approach? When function evaluation gets stuck, the method [`org.kframework.rewriter.Rewriter.execute`](https://github.com/kframework/k/blob/master/kore/src/main/scala/org/kframework/rewriter/Rewriter.scala#L23)  throws an exception containing the stacktrace, and the exception is caught and pretty-printed in [`org.kframework.krun.KRun.run`](https://github.com/kframework/k/blob/master/kernel/src/main/java/org/kframework/krun/KRun.java#L87-L93).

Another question is how would the OCaml backend return the stacktrace back. I suggest adding a new line with an `ok`/`error` flag to the [output file](https://github.com/kframework/k/blob/master/ocaml-backend/src/main/java/org/kframework/backend/ocaml/OcamlRewriter.java#L131-L138). If the function evaluation gets stuck, the file will contain the `error` flag and instead of single configuration there would be a `List` of them.

@chathhorn FYI

2018-09-24 15:50 UTC, dwightguth commented
One thing you could do if you wanted is just to construct a term of sort List instead of a list of terms of various sorts. So if `foo()` called `bar(1)` which called `1 /Int 0`, then you would return `ListItem(foo()) ListItem(bar(1)) ListItem(1 /Int 0)` from the ocaml backend.

2018-09-24 15:51 UTC, dwightguth commented
If you do that, you don't necessarily even have to print it in any special way, but of course you could, since any term returned by the backend which was of sort List would be known to be an error.

2018-09-24 16:27 UTC, h0nzZik commented
Yes, I meant I would print `ListItem(LastConfiguration) ListItem(bar(1)) ListItem(1 /Int 0)`. I still prefer to have some `ok`/`error` flags - I think that in principle the backends could do any kind of term rewriting, and a term of sort `List` is still a valid term, so it does not indicate an error.

2018-12-05 16:05 UTC, h0nzZik commented
Closed in favour of https://github.com/kframework/k/pull/167.

2018-12-05 16:05 UTC, closed without merging