Rat
runtimeverification/k pull request #785
Opened 2019-09-16 21:41 UTC by daejunpark

2019-09-16 21:43 UTC, daejunpark commented
@dwightguth Parsing `4.a` failed without the bracket syntax. Any idea?
https://github.com/kframework/k/pull/779/files/e7163539eac57316c66f7a645da1a0c3792e6ba1#diff-a746214946bd52f7ecf6d3897b8e510a

2019-09-16 21:55 UTC, dwightguth commented
put the bracket in the syntax module, not in the RAT module. That's where it belongs.

2019-09-16 22:24 UTC, daejunpark commented
@dwightguth please review. changes:
- address your comments in the previous PR
- add the java version of the tests

2019-09-17 13:13 UTC, dwightguth requested changes

2019-09-17 13:13 UTC, dwightguth commented on k-distribution/tests/regression-new/rat/java/a.k
> +requires "rat.k"
Let's make this a symlink to the other definition.

2019-09-17 16:11 UTC, daejunpark commented
@dwightguth `java/a.k` is slightly different from `haskell/a.k`, so I factored out the common part.  Also, I made the duplicate `java/*.out` a symlink to `haskell/*.out`. Please re-review.

2019-09-19 20:50 UTC, dwightguth commented on k-distribution/include/builtin/rat.k
> +  rule < I , I' >Rat ==Rat < J , J' >Rat => I ==Int J andBool I' ==Int J'
as I believe I said elsewhere, this module should be given the attribute [kast] and imported from RAT rather than the other way around.

2019-09-23 18:47 UTC, dwightguth approved these changes

2019-09-23 20:25 UTC, merged