Making ambiguities as errors
runtimeverification/k pull request #831
Opened 2019-10-09 14:14 UTC by radumereuta

also adding --keep-amb for debugging purposes

This should be a fix for #828

2019-10-11 15:11 UTC, radumereuta commented
@dwightguth please review.

2019-10-15 16:14 UTC, dwightguth requested changes
I haven't looked over this in detail, but let's remove the --keep-amb flag. You can make a separate PR for that if you want, but I'd like to keep this PR focused on reporting ambiguities as errors.

2019-10-15 16:14 UTC, dwightguth commented on k-distribution/tests/regression-new/context-alias/test.k
> -syntax Expr ::= Expr "+" Expr [strict(heatable)]
I'd like us to wait to merge this PR until my PR fixing this particular set of tests in a better way is merged.

2019-10-15 17:16 UTC, radumereuta commented on k-distribution/tests/regression-new/context-alias/test.k
> -syntax Expr ::= Expr "+" Expr [strict(heatable)]
Let me know when that's done and I'll come back to this.

2019-10-29 16:39 UTC, closed without merging