Make ambiguities report as errors - b
runtimeverification/k pull request #855
Opened 2019-10-29 16:38 UTC by radumereuta

Fix for #828

2019-10-29 20:02 UTC, dwightguth requested changes
I'm not comfortable with tests being deleted without justification. Please explain why you have deleted some tests in this PR.

2019-10-29 21:11 UTC, radumereuta commented
Also sent to the #k channel:
I only removed test 2 and 3, there is another one which tests for `[Error] Compiler: Could not find main syntax module with name TEST-SYNTAX in definition.  Use --syntax-module to specify one. Using TEST as default.`

2019-10-30 21:25 UTC, radumereuta commented
@dwightguth please review.
I've added the test as you asked.
I also found a bug related to cached error messages.

2019-10-31 20:19 UTC, dwightguth approved these changes

2019-11-01 09:17 UTC, merged